
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { useAuth } from '@/context/AuthContext';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { useQueryClient } from '@tanstack/react-query';
import { toast } from '@/components/ui/use-toast';
import { Building, UserCircle } from 'lucide-react';

const formSchema = z.object({
  first_name: z.string().min(2, "First name must be at least 2 characters."),
  last_name: z.string().min(2, "Last name must be at least 2 characters."),
  phone: z.string().optional(),
  designation: z.string().min(2, "Designation is required."),
  title: z.string().min(2, "Title is required."),
});

type FormValues = z.infer<typeof formSchema>;

const EmployeeSetup = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [loading, setLoading] = useState(false);

  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      first_name: '',
      last_name: '',
      phone: '',
      designation: '',
      title: '',
    },
  });

  const onSubmit = async (values: FormValues) => {
    if (!user) {
      toast({
        title: "Authentication Error",
        description: "You must be logged in.",
        variant: "destructive",
      });
      return;
    }
    setLoading(true);

    try {
      // Check if this is the first employee to be created
      const { count, error: countError } = await supabase
        .from('employees')
        .select('*', { count: 'exact', head: true });

      if (countError) throw countError;
      
      const role = count === 0 ? 'admin' : 'employee';

      const { error: insertError } = await supabase.from('employees').insert({
        user_id: user.id,
        company_owner_id: user.id,
        email: user.email,
        first_name: values.first_name,
        last_name: values.last_name,
        phone: values.phone,
        designation: values.designation,
        title: values.title,
        role: role,
        status: 'active',
        // This field is required by the TS types, but the value will be generated by a DB trigger.
        // We pass an empty string to satisfy the type.
        employee_number: '',
      });

      if (insertError) throw insertError;
      
      await queryClient.invalidateQueries({ queryKey: ['employeeProfile', user.id] });
      
      toast({
        title: "Profile Created!",
        description: "Welcome! Your employee profile has been set up.",
      });

      if (role === 'admin') {
        toast({
          title: "You are the Admin!",
          description: "You have been assigned administrative privileges.",
          className: "bg-gradient-to-r from-quikle-primary to-quikle-secondary text-white",
        });
      }
      
      navigate('/dashboard');

    } catch (error: any) {
      toast({
        title: "Error",
        description: `Failed to create profile: ${error.message}`,
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex justify-center items-center min-h-[calc(100vh-200px)]">
      <Card className="w-full max-w-2xl bg-gradient-to-br from-white via-quikle-crystal to-quikle-platinum border-quikle-silver/30 shadow-luxury">
        <CardHeader className="text-center border-b border-quikle-silver/20 pb-4">
          <CardTitle className="text-2xl font-bold bg-gradient-to-r from-quikle-primary to-quikle-secondary bg-clip-text text-transparent">
            Welcome to Quikle CRM!
          </CardTitle>
          <CardDescription className="text-quikle-slate">
            Let's set up your employee profile to get you started.
          </CardDescription>
        </CardHeader>
        <CardContent className="pt-6">
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <div className="space-y-4">
                <h3 className="text-lg font-medium text-quikle-charcoal flex items-center gap-2"><UserCircle/> Personal Information</h3>
                 <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <FormField control={form.control} name="first_name" render={({ field }) => (
                      <FormItem>
                        <FormLabel>First Name</FormLabel>
                        <FormControl><Input placeholder="John" {...field} /></FormControl>
                        <FormMessage />
                      </FormItem>
                    )} />
                    <FormField control={form.control} name="last_name" render={({ field }) => (
                      <FormItem>
                        <FormLabel>Last Name</FormLabel>
                        <FormControl><Input placeholder="Smith" {...field} /></FormControl>
                        <FormMessage />
                      </FormItem>
                    )} />
                 </div>
              </div>
              <div className="space-y-4">
                <h3 className="text-lg font-medium text-quikle-charcoal flex items-center gap-2"><Building/> Company Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <FormField control={form.control} name="phone" render={({ field }) => (
                    <FormItem>
                      <FormLabel>Phone Number (Optional)</FormLabel>
                      <FormControl><Input placeholder="(555) 123-4567" {...field} /></FormControl>
                      <FormMessage />
                    </FormItem>
                  )} />
                  <FormField control={form.control} name="designation" render={({ field }) => (
                    <FormItem>
                      <FormLabel>Your Designation</FormLabel>
                      <FormControl><Input placeholder="e.g., Sales Manager" {...field} /></FormControl>
                      <FormMessage />
                    </FormItem>
                  )} />
                  <FormField control={form.control} name="title" render={({ field }) => (
                    <FormItem>
                      <FormLabel>Your Title</FormLabel>
                      <FormControl><Input placeholder="e.g., Founder, CEO" {...field} /></FormControl>
                      <FormMessage />
                    </FormItem>
                  )} />
                </div>
              </div>
              <div className="flex justify-end pt-4">
                <Button type="submit" className="quikle-button-primary" disabled={loading}>
                  {loading ? 'Saving Profile...' : 'Complete Setup'}
                </Button>
              </div>
            </form>
          </Form>
        </CardContent>
      </Card>
    </div>
  );
};

export default EmployeeSetup;
