
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oquiaxbnkdnpixqhqdfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xdWlheGJua2RucGl4cWhxZGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTcyOTYsImV4cCI6MjA2MjEzMzI5Nn0.K6OhS4jbjR-2MnMGPKym6VynV3zFI0bC0QbVMURLwg4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
  }
});
